blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('posts/<int:id>/comments/', views.add_comment_view, name='comment'),
    path('posts/today/', views.today_post_view, name='today_post'),
    path('posts/most-popular/', views.popular_posts_view, name='popular_posts'),
    path('posts/latest/', views.latest_posts_view, name='latest_posts'),
    path('posts/<slug:slugname>/', views.post_view, name='post'),
    path('posts/<slug:slugname>/vote/<int:vote>/', views.vote_view, name='vote'),
    path('categories/<slug:slugname>/', views.category_view, name='category'),
    path('sign-out/', views.sign_out_view, name='sign_out'),
    path('sign-in/', views.sign_in_view, name='sign_in'),
    path('accounts/login/', views.sign_in_view, name='sign_in'),
    path('sign-up/', views.sign_up_view, name='sign_up'),





]

django_blog/urls.py
"""django_blog URL Configuration

"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
import random

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone


# INFO  BlogPostCategory
class BlogPostCategory(models.Model):
    title = models.CharField(max_length=120, unique=True)
    tags = models.TextField()
    slug_field = models.SlugField(
        null=True, max_length=128, unique=True, editable=False)

    class Meta:
        verbose_name_plural = 'Blog post categories'

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'slugname': self.slug_field})

    def __str__(self):
        return self.title


# INFO BlogPost Model
class BlogPost(models.Model):
    title = models.CharField(max_length=128)
    drafted = models.DateTimeField(auto_now_add=True)
    slug_field = models.SlugField(
        max_length=128, unique=True, editable=False, null=True)
    published = models.BooleanField(default=False)
    pub_date = models.DateTimeField(null=True, editable=False)
    tags = models.TextField(blank=True)
    author = models.ForeignKey(get_user_model(
    ), related_name='authored_posts', on_delete=models.SET_NULL, null=True)
    upvotes = models.PositiveBigIntegerField(default=0)
    downvotes = models.PositiveBigIntegerField(default=0)
    category = models.ForeignKey(
        BlogPostCategory, related_name='posts', on_delete=models.SET_NULL, null=True)
    cover = models.ImageField(null=True)
    layout = models.PositiveSmallIntegerField(default=0)

    def get_parts(self):
        articles = self.articles.all()
        images = self.imgs.all()
        parts = list(articles) + list(images)
        def func(next): return next.layout_id
        sorted_parts = sorted(parts, key=func)
        return sorted_parts

    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'slugname': self.slug_field})

    def get_intro_text(self):
        if self.articles.count() == 0:
            return ''
        return self.articles.all()[0].content[:128]

    def get_mock_cover(self):
        temp = random.randint(1, 7)
        return '/static/blog/img/pic{0}.jpg'.format(temp)

    def get_pub_date(self):
        if not self.pub_date:
            return timezone.now()

    def __str__(self) -> str:
        return self.title


# INFO PostArticle
class PostArticle(models.Model):
    heading = models.CharField(max_length=128, null=True, blank=True)
    content = models.TextField(blank=False)
    published = models.BooleanField(default=False)
    layout_id = models.PositiveSmallIntegerField(null=True)
    post = models.ForeignKey(
        BlogPost, related_name='articles', on_delete=models.CASCADE)

    def __str__(self):
        return self.content[:64]

    def is_article(self):
        return True

    def is_image(self):
        return False


# INFO PostImage


class PostImage(models.Model):
    caption = models.CharField(max_length=64)
    file = models.ImageField(blank=True, null=True)
    layout_id = models.PositiveSmallIntegerField(null=True)
    post = models.ForeignKey(
        BlogPost, related_name='imgs', on_delete=models.CASCADE)

    def __str__(self):
        return 'IMG {0}'.format(self.id)

    def is_article(self):
        return False

    def is_image(self):
        return True

# INFO PostComment


class PostComment(models.Model):
    post = models.ForeignKey(
        BlogPost, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(
        get_user_model(), related_name='authored_comments', on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=1024)
    likes = models.PositiveSmallIntegerField(default=0)

    class Meta:
        ordering = ['-pub_date', ]

    def __str__(self):
        return "COMMENT {0}".format(self.id)


# INFO CommentReply
class CommentReply(models.Model):
    comment = models.ForeignKey(
        PostComment, related_name='replies', on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        get_user_model(), related_name='authored_replies', on_delete=models.CASCADE)
    content = models.CharField(max_length=512)

    class Meta:
        verbose_name_plural = 'Comment replies'

    def __str__(self):
        return 'REPLY {0}'.format(self.id)

blog/forms.py
from django import forms


class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=1024, label='Comment')


class SignInForm(forms.Form):
    email = forms.EmailField(required=True, label='email', max_length=255)
    password = forms.CharField(max_length=25, required=True, label='password')


class SignUpForm(SignInForm):
    fn = forms.CharField(max_length=35, required=True, label='fn')
    ln = forms.CharField(max_length=35, required=True, label='ln')

blog/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from users.models import BlogUser

from blog.models import BlogPost, BlogPostCategory, PostComment

from .forms import CommentForm, SignInForm, SignUpForm


# Index View
def index_view(request):
    categories = BlogPostCategory.objects.all()
    featured_categories = list(categories.order_by('?'))
    featured_categories = [
        cat for cat in featured_categories if cat.posts.count() > 0][:6]

    posts = BlogPost.objects.all()
    featured_categories = categories.order_by('?')[:6]
    context = {
        'categories': categories,
        'posts': posts,
        'featured_categories': featured_categories
    }
    return render(request, 'blog/index.html', context)


# Latest Posts View
def latest_posts_view(request):
    categories = BlogPostCategory.objects.all()
    featured_categories = list(categories.order_by('?'))
    featured_categories = [
        cat for cat in featured_categories if cat.posts.count() > 0][:6]
    posts = BlogPost.objects.order_by('-pub_date').all()
    context = {
        'posts': posts,
        'featured_categories': featured_categories,
        'categories': categories
    }
    return render(request, 'blog/latest.html', context)


# Most popular Posts View
def popular_posts_view(request):
    categories = BlogPostCategory.objects.all()
    featured_categories = list(categories.order_by('?'))
    featured_categories = [
        cat for cat in featured_categories if cat.posts.count() > 0][:6]
    posts = BlogPost.objects.order_by('-upvotes').all()
    context = {
        'posts': posts,
        'featured_categories': featured_categories,
        'categories': categories
    }
    return render(request, 'blog/popular.html', context)


# AddComment
@login_required
def add_comment_view(request, id):
    current_user = request.user
    post = get_object_or_404(BlogPost, id=id)
    form = CommentForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        PostComment.objects.create(
            content=cd['comment'],
            author=current_user,
            post=post
        )
        return redirect(reverse('blog:post', args=[post.slug_field]))
    else:
        context = {
            'commment_form': form,
            'notice': 'Your comment has been added'
        }

        return render(request, 'blog/post.html', context)


# Vote View
@login_required
def vote_view(request, slugname, vote):
    post = get_object_or_404(BlogPost, slug_field=slugname)
    if int(vote) == 1:
        post.upvotes += 1
        post.save()
    elif int(vote) == 0:
        post.downvotes += 1
        post.save()

    if not request.session.get('voted_post_ids', None):
        request.session['voted_post_ids'] = [post.id, ]
    else:
        request.session.get('voted_post_ids').append(post.id)

    return redirect(reverse('blog:post', args=[slugname]))


# Today Post View
def today_post_view(request):
    post = BlogPost.objects.order_by('?').all()[0]
    show_votes = not(post.id in request.session.get('voted_post_ids', []))
    context = {
        'post': post,
        'show_votes': show_votes,


    }
    return render(request, 'blog/post.html', context)


# Sign out view
def sign_out_view(request):
    logout(request)
    request.session.flush()
    return redirect('/')

# sign in view


def sign_in_view(request):
    if request.method == 'GET':
        categories = BlogPostCategory.objects.all()
        featured_categories = list(categories.order_by('?'))
        featured_categories = [
            cat for cat in featured_categories if cat.posts.count() > 0][:6]
        context = {
            'categories': categories,
            'featured_categories': featured_categories,
        }
        return render(request, 'blog/sign_in.html', context)

    if request.method == 'POST':
        form = SignInForm(request.POST)
        categories = BlogPostCategory.objects.all()
        featured_categories = list(categories.order_by('?'))
        featured_categories = [
            cat for cat in featured_categories if cat.posts.count() > 0][:6]
        if not form.is_valid():
            context = {
                'form': form,
                'categories': categories,
                'featured_categories': featured_categories,
            }
            return render(request, 'blog/sign_in.html', context)

        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(username=email,  password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            return render(request, 'blog/sign_in.html', context={
                'message': 'Incorrect email or password',
                'categories': categories,
                'featured_categories': featured_categories,
            })


# sign up view


def sign_up_view(request):
    if request.method == 'GET':
        categories = BlogPostCategory.objects.all()
        featured_categories = list(categories.order_by('?'))
        featured_categories = [
            cat for cat in featured_categories if cat.posts.count() > 0][:6]
        context = {
            'categories': categories,
            'featured_categories': featured_categories,
        }
        return render(request, 'blog/sign_up.html', context)

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        categories = BlogPostCategory.objects.all()
        featured_categories = list(categories.order_by('?'))
        featured_categories = [
            cat for cat in featured_categories if cat.posts.count() > 0][:6]
        if not form.is_valid():
            context = {
                'form': form,
                'categories': categories,
                'featured_categories': featured_categories,
            }
            return render(request, 'blog/sign_up.html', context)

        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        fn = form.cleaned_data['fn']
        ln = form.cleaned_data['ln']
        BlogUser.objects.create_user(
            firstname=fn,
            lastname=ln,
            email=email,
            password=password,

        )
        return redirect('/sign-in/')


# Post View
def post_view(request, slugname):
    post = get_object_or_404(BlogPost, slug_field=slugname)
    categories = BlogPostCategory.objects.all()
    featured_categories = list(categories.order_by('?'))
    featured_categories = [
        cat for cat in featured_categories if cat.posts.count() > 0][:6]
    show_votes = not(post.id in request.session.get('voted_post_ids', []))
    context = {
        'post': post,
        'categories': categories,
        'featured_categories': featured_categories,
        'show_votes': show_votes,
    }
    return render(request, 'blog/post.html', context)


# Category View
def category_view(request, slugname):
    category = get_object_or_404(BlogPostCategory, slug_field=slugname)
    categories = BlogPostCategory.objects.all()
    featured_categories = list(categories.order_by('?'))
    featured_categories = [
        cat for cat in featured_categories if cat.posts.count() > 0][:6]
    context = {
        'category': category,
        'categories': categories,
        'featured_categories': featured_categories,
        'posts': category.posts.all(),
    }
    return render(request, 'blog/category.html', context)

blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% load static %}

{% block main %}

<div class='sticky top-16 z-10 bg-white shadow-sm left-0 right-0 mx-auto   p-2'>
    <p class='p-4 text-xl text-gray-700 font-bold capitalize lg:text-2xl'><i
           class="bi-bullseye text-2xl "></i> {{category.title}}
    </p>
</div>

{{block.super}}


{% endblock main %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}

blog/templates/blog/latest.html
{% extends 'blog/base.html' %}
{% load static %}

{% block main %}

<div class='sticky top-16 z-10 bg-white shadow-sm left-0 right-0 mx-auto   p-2'>
    <p class='p-4 text-xl text-gray-700 font-bold capitalize lg:text-2xl'><i
           class="bi-lightning text-2xl "></i> Latest
    </p>
</div>

{{block.super}}


{% endblock main %}

blog/templates/blog/popular.html
{% extends 'blog/base.html' %}
{% load static %}

{% block main %}
<div class='sticky top-16 z-10 bg-white shadow-sm  left-0 right-0 mx-auto   p-2'>
    <p class='p-4 text-xl text-gray-700 font-bold capitalize lg:text-2xl'><i
           class="bi-brightness-high text-2xl "></i> Most popular
    </p>
</div>

{{block.super}}

{% endblock main %}

blog/templates/blog/post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block main %}


<div class="bg-white max-w-5xl  mx-auto  p-4">

    <h1 style="font-family: Georgia, 'Times New Roman', Times, serif;"
        class='text-2xl lg:text-6xl  font-bold text-left  p-2 lg:p-8 w-full lg:w-10/12 mx-auto mb-8'>
        {{post.title}}</h1>

    <div style="font-family: Georgia, 'Times New Roman', Times, serif;"
         class='my-4 ml-1 lg:ml-4  '>
        <p class='text-white shadow-lg my-2 lg:font-light inline-block bg-gray-700  p-2 text-xs'>
            Published:
            {{post.get_pub_date}}
        </p>
        <br>

        <p class='text-white shadow-lg lg:font-light inline-block bg-gray-700  p-2 text-xs'>
            Author:
            {{post.author.get_full_name}}</p>
    </div>


    <div>
        {% if post.cover %}
        <img height="200px"
             class='block lg:rounded text-xs mb-4 mx-2 lg:mx-0 w-full mx-auto'
             src='{{post.get_mock_cover}}'
             alt='{{post.title}}'>

        {% endif %}


        {% for part in post.get_parts %}

        {% if part.is_article %}

        {% if part.heading %}
        <h2 class='text-left mx-1 p-4  font-bold text-xl   lg:text-4xl text-gray-900 '>
            {{part.heading}}</h2>
        {% endif %}


        <p
           class='text-md lg:text-3xl first-letter lg-line-height sm-line-height overflow-x-hidden text-indent  lg:p-4 lg:opacity-90 '>
            {{part.content}}


        </p>

        {% elif part.is_image %}

        <img height="200px"
             class='block lg:rounded text-xs mb-2 mt-3 mx-2 lg:mx-0 w-full mx-auto'
             src='{{post.get_mock_cover}}'
             alt='{{part.caption}}'>

        <p class='opacity-80 text-lg lg:text-xl text-center p-2 mb-4 lg:bg-gray-200 '>
            {{part.caption}} </p>

        {% endif %}

        {% endfor  %}

        <div class='my-4'>
            <hr>
            <p style='font-family:cursive'
               class='p-6 opacity-90 text-lg lg:text-2xl inline-block'>{{post.get_pub_date}}</p>
            <span style='font-family:cursive'
                  class='text-sm lg:text-lg text-blue-900 opacity-95 align-middle inline-block   text-gray-500 rounded-xl font-black  p-2 px-8'>{{post.category.title}}</span>
            <hr>
        </div>


    </div>

    <!-- <div class='flex flex-row justify-around  bg-gray-200 bg-white  rounded  '>

        <button class='flex-grow'> <i
               class='bi-hand-thumbs-down text-red-500  p-2 px-4 lg:p-4 rounded text-2xl  lg:text-3xl inline-block mx-auto '></i>
            <span class='text-sm text-center text-red-500'>{{post.downvotes}}</span></button>

        <button class='flex-grow'> <i
               class='bi-hand-thumbs-up text-green-500  p-2 px-4  lg:p-4 rounded text-2xl lg:text-3xl inline-block mx-auto'></i>
            <span class='text-sm text-center text-green-500'>{{post.upvotes}}</span> </button>



    </div> -->


</div>


{% if show_votes %}
<div
     class='flex flex-row justify-around z-20 sticky bottom-0 left-0 right-0 bg-gray-200 lg:bg-gray-100 lg:shadow  rounded  '>
    <a href='{% url "blog:vote" post.slug_field "0" %}'><button class='flex-grow'> <i
               class='bi-hand-thumbs-down text-red-500 hover:bg-red-500 hover:text-white p-2 px-4 lg:p-4 rounded text-2xl  lg:text-3xl inline-block mx-auto '></i><span
                  class='text-sm text-center text-red-500'>{{post.downvotes}}</span></button></a>

    <a href='{% url "blog:vote" post.slug_field "1" %}'><button class='flex-grow'> <i
               class='bi-hand-thumbs-up text-green-500 hover:bg-green-500 hover:text-white p-2 px-4  lg:p-4 rounded text-2xl lg:text-3xl inline-block mx-auto'></i><span
                  class='text-sm text-center text-green-500'>{{post.upvotes}}</span></button>
    </a>

</div>

{% endif %}



<div class='m-2 .max-height p-4 lg:max-w-2xl mx-auto mb-8'>
    <hr>
    <p
       class='font-bold text-xl sticky top-12 z-30 inline-block mx-auto  rounded-xl left-0 right-0 opacity-90 p-4  text-center text-gray-900'>
        <i class='bi-chat text-2xl'></i> Comments
    </p>



    <div>
        {% if not request.user.is_authenticated %}
        <hr>

        <p class='text-center text-sm p-4 lg:text-base font-bold text-yellow-500'> Sign in to leave
            a comment and see who posts what
            <hr>
        </p>

        {% else %}




        <div class=' '>
            <form method='post'
                  action='{% url "blog:comment" post.id %}'>

                {% csrf_token %}
                <textarea class='pt-8 outline-none pl-8 resize-none pr-2 pb-8 lg:p-16 border-2 text-lg w-full border-opacity-80 placeholder-gray-300 my-4 border-gray-300 border-solid rounded-lg'
                          name='comment'
                          required
                          placeholder='Leave a comment'>.</textarea>

                <button class='w-full p-2 lg:p-6 rounded text-xl font-normal hover:bg-green-600 bg-green-700 text-white text-center '
                        role='button'
                        type='submit'> Submit </button>
            </form>
        </div>
        <hr>

        {% endif %}


        {% for comment in post.comments.all  %}
        <div class='bg-gray-200 relative rounded p-4 overflow-x-hidden overflow-y-hidden my-8'>
            <i class='bi-person-circle text-2xl opacity-80 '></i> &nbsp;&nbsp;
            <span class='font-bold p-3 capitalize text-center opacity-95'>
                {%if request.user.is_authenticated %}
                {{comment.author.get_full_name}}
                {% else %}
                Anonymous
                {% endif %}
            </span>
            <p style="font-family: Georgia, 'Times New Roman', Times, serif;"
               class='p-2 py-4 text-gray-600 text-base lg:text-xl'>{{comment.content}}</p>

            <div>
                <i class='bi-clock text-gray-700'></i>
                <span class='text-xs lg:text-sm'>{{comment.pub_date}}</span>
                {% if request.user.is_authenticated %}
                <button class='absolute bottom-0 right-0'><i
                       class='bi-hand-thumbs-up p-2 text-2xl rounded-lg hover:bg-gray-500 bg-gray-300'></i></button>
                {% endif %}
            </div>
        </div>
        {% endfor  %}
    </div>




</div>


<div class='bg-gray-800 text-white  py-16'>

    <div class='flex-col lg:flex-row justify-center space-y-8 content-center'>

        <ul
            class='flex-col text-center text-xs space-x-12 lg:text-sm lg:flex-row justify-evenly content-center'>
            <a href='/'> Home </a>
            <a href='/posts/today/'> Today </a>
            <a href='/posts/latest/'> Latest </a>
            <a href='/posts/most-popular/'> Most read </a>



        </ul>


        <ul
            class='flex-col text-center text-xs space-x-8 lg:text-sm lg:flex-row justify-evenly content-center'>
            <span class='cursor-pointer'
                  title='{{host}}'>Host </span>
            <span class='cursor-pointer'
                  title='{{framework}}'>Framework </span>
            <span class='cursor-pointer'
                  title='{{language}}'>Language </span>
            <span class='cursor-pointer'
                  title='{{developer}}'>Developer </span>



        </ul>


        <ul
            class='flex-col text-center pt-8 text-xs space-x-12 lg:text-sm lg:flex-row justify-evenly content-center'>
            <a href='http://facebook.com/timmypelumy/'> <i class='bi-facebook text-xl'></i> </a>
            <a href='http://linkedin.com/in/timmypelumy/'> <i class='bi-linkedin text-xl'></i> </a>
            <a href='http://twitter.com/timmypelumy/'> <i class='bi-twitter text-xl'></i> </a>
            <a href='http://github.com/timmypelumy/'> <i class='bi-github text-xl'></i> </a>



        </ul>

        <p class='text-center text-xs pt-8 lg:text-sm'> &copy; {% now "Y" %} </p>

    </div>





</div>


{% endblock main %}

blog/templates/blog/sign_in.html
{% extends 'blog/base.html' %}
{% load static %}

{% block main %}

<div class='sticky top-16 z-10 bg-white shadow-sm left-0 right-0 mx-auto   p-2'>
    <p class='p-4 text-xl text-gray-700 font-bold capitalize lg:text-2xl'><i
           class="bi-person text-2xl "></i> Sign in
    </p>
</div>

<form method='post'
      action='/sign-in/'
      class='max-w-lg mx-auto bg-gray-200 p-8'>



    {% csrf_token %}

    {% if message %}
    <p class='text-yellow-600 text-base lg:text-xl font-semibold px-4'> {{message}}</p>
    {% endif %}



    <div class='mx-2 my-8'>

        <input type='email'
               name='email'
               class='px-8 w-full    outline-none py-3 lg:py-6 block rounded-xl placeholder-90'
               placeholder='Email address'
               required>
        <span class='text-red-500 mx-2  inline-block p-4'>{{form.email.errors}}</span>


    </div>



    <div class='mx-2 my-8'>

        <input type='password'
               name='password'
               class='px-8 w-full   outline-none py-3 lg:py-6 block rounded-xl placeholder-90'
               placeholder='Password'
               required>
        <span class='text-red-500 mx-2 inline-block p-4'>{{form.password.errors}}</span>

    </div>

    <input type='submit'
           class='p-3 px-6 lg:py-6 w-full outline-none  block rounded text-xl text-center bg-green-600 hover:bg-green-500 text-white'
           value='Sign in'>


</form>






{% endblock main %}

blog/templates/blog/sign_up.html
{% extends 'blog/base.html' %}
{% load static %}

{% block main %}

<div class='sticky top-16 z-10 bg-white shadow-sm left-0 right-0 mx-auto   p-2'>
    <p class='p-4 text-xl text-gray-700 font-bold capitalize lg:text-2xl'><i
           class="bi-person text-2xl "></i> Create an account
    </p>
</div>

<form method='post'
      action='/sign-up/'
      class='max-w-lg mx-auto bg-gray-200 p-8'>



    {% csrf_token %}

    {% if message %}
    <p class='text-yellow-600 text-base lg:text-xl font-semibold px-4'> {{message}}</p>


    {% endif %}


    <div class='mx-2 my-8'>

        <input type='text'
               name='fn'
               class='px-8 w-full   outline-none py-3 lg:py-6 block rounded-xl placeholder-90'
               placeholder='Firstname'
               required>
        <span class='text-red-500 mx-2 inline-block p-4'>{{form.fn.errors}}</span>

    </div>

    <div class='mx-2 my-8'>

        <input type='text'
               name='ln'
               class='px-8 w-full   outline-none py-3 lg:py-6 block rounded-xl placeholder-90'
               placeholder='Lastname'
               required>
        <span class='text-red-500 mx-2 inline-block p-4'>{{form.ln.errors}}</span>

    </div>



    <div class='mx-2 my-8'>

        <input type='email'
               name='email'
               class='px-8 w-full    outline-none py-3 lg:py-6 block rounded-xl placeholder-90'
               placeholder='Email address'
               required>
        <span class='text-red-500 mx-2  inline-block p-4'>{{form.email.errors}}</span>


    </div>



    <div class='mx-2 my-8'>

        <input type='password'
               name='password'
               class='px-8 w-full   outline-none py-3 lg:py-6 block rounded-xl placeholder-90'
               placeholder='Password'
               required>
        <span class='text-red-500 mx-2 inline-block p-4'>{{form.password.errors}}</span>

    </div>

    <input type='submit'
           class='p-3 px-6 lg:py-6 w-full outline-none  block rounded text-xl text-center bg-green-600 hover:bg-green-500 text-white'
           value='Submit'>


</form>





{% endblock main %}